using System;

namespace UbytkacAdmin.Classes {

    /// <summary>
    /// Typical Table schema for API which you copy from Generated Model in Backend Server On
    /// Backend server is Automatically generated by Scaffold command
    /// </summary>
    public partial class TemplateClassList {
        public int Id { get; set; } = 0;
        public string Name { get; set; } = null;
        public string Description { get; set; } = null;
        public int UserId { get; set; }
        public bool Active { get; set; }
        public DateTime TimeStamp { get; set; }
    }

    /// <summary>
    /// If you Add the field with same name as joined table in Database Model you must set this
    /// field as 'null' before send Insert / Update
    /// </summary>
    public partial class TemplateClassListWithLocalTranslation {
        public int Id { get; set; } = 0;
        public string Name { get; set; } = null;
        public string Description { get; set; } = null;
        public int UserId { get; set; }
        public bool Active { get; set; }
        public DateTime TimeStamp { get; set; }

        public string Translation { get; set; } = null;
    }

    /// <summary>
    /// Extend API class with custom Collumn separately
    /// </summary>
    public partial class ExtendedTemplateClassList : TemplateClassList {
        public string TotalCurrency { get; set; }
    }
}